### ISSUE TITLE
Please support the 3rd type of node selector, "updater"

### ISSUE THREAD

**Issue by joeblade** [openweb-nl/hippo-groovy-updater#12]
Since hippo 1 1 (it seems) there is a 3rd way to select nodes for the updater:

https://documentation.bloomreach.com/11/library/concepts/update/using-the-updater-editor.html

Under "Executing Updater Scripts" you will find the option "Updater" which means the script itself will provide the nodes on which it should operate.

I wrote a script (which I am planning to make into a base-class) that allows nodes to be inserted as parameters for the situations where we would run on specific paths. It would be nice if this can be bootstrapped using the hippo-groovy-updater tool.

**Comment by joostoudeman** [comment]
Looks like this is running the updater based fully on the script. We could probably support it by enabling using @Updater without either path or xpath.

**Comment by joeblade** [comment]
The only issue would be if there's a future update that adds another mode
that needs no configuration. That scenario might make backward
compatibility problematic.
I guess a type param ('updater' as default, 'imaginary additional mode',
xpath, path)  could be added in the future if that did happen. (or just not
be backward compatible)

**Comment by joostoudeman** [comment]
@joeblade We'll follow the example of BloomReach. If you check org.onehippo.repository.update.UpdaterExecutor#execute you'll see they do the same. It already works for the maven plugin. All we need to do if fix it for the updatersync-module.

**Comment by joostoudeman** [comment]
Minor update, I was apparently still working with an old version. This is all already supported by the newest version. When not supplying an xpath or path, the script will be managing the node selection. This is also true for the updatersync module.
However, I do want to add some unit tests, so I'll leave this issue open until I made them.

**Comment by joostoudeman** [comment]
Tests are created
