### ISSUE TITLE
YAML config doesn't get reloaded

### ISSUE THREAD

**Issue by mxdrenthe** [openweb-nl/hippo-groovy-updater#9]
When using the plugin on local development the scripts get reloaded.
If you distribute the script to a non-development environment it doesn't get reloaded

Expected behavior would be that when scripts have changed they are getting reloaded on non-development environment.

**Comment by mxdrenthe** [comment]
The problem is created because all scripts are marked as content. When this is already there BrXM won't reload the script.

Moving scripts into config it get reloaded every time it is changed. Suggested is to only do this for items placed in 'registry' the are ment to long live inside BrXM

**Comment by joostoudeman** [comment]
I added the label 'bug' since it does work for the xml style. A branch is created for fixing bootstrap reload. Completely untested so far.
